### ISSUE TITLE
Creating a feature to change the screen size accordingly

### ISSUE THREAD

**Issue by metallego** [metallego/2D-AppGroupProject#2]
This feature would allow the user to set the screen resolution to whatever size they desire. With this feature a good chunk of the revamps would be in the optionspane.java file. I will most likely have to make a new class for this feature since currently there is only the volume on/off switch on it so far. I will also most likely have to make edits to the main app java file since there I set the window's resolution already before it launches. So that means I will have to work on editing the main so that it can grab any new versions of the resolutions if the user makes any edits on the options panel. Then I would also have to see if that would affect the other game options specifically affecting the levels/enemies/hero/chests/etc.

**Comment by onzfonz** [comment]
This one right here is good.  If you can't get the resolution to dynamically change, I would even say to try to make it so that the screen resolution could be changed in a file and then when it is restarted it still works well, so like having a preferences file for the resolution but if not, just having the resolution in one of the classes or via the options pane would be good to move forward with.

**Comment by metallego** [comment]
1. Run the application.
2. Go to the options pane.
3. Select one of the screen resolution options.
4. Once the app closes rerun the application To see the changes.
